### ISSUE TITLE
Can't figure out how this works

### ISSUE THREAD

**Issue by Sam8500** [Mobius1/vPrompt#4]
Hello, first of all I think your script looks great but I'm having trouble understanding how to use it. I installed the script and added it to the manifest, added the lines in my code but it looks buggy and is making me lag. Here's an example of how it looks: ![image](https://user-images.githubusercontent.com/99142544/167261720-07e532dc-4b9f-4746-8183-414ec567fb19.png) ![image](https://user-images.githubusercontent.com/99142544/167261734-dccb6704-9c47-4c02-8218-2f75195856fc.png)

**Comment by TrAsKiN** [comment]
I advise you to look at the solutions proposed here: #1, #2.

**Comment by Sam8500** [comment]
I did but I don't think it's the same problem, the ui shows up in the top left corner aswell and it just doesn't work

**Comment by TrAsKiN** [comment]
I see. You create a new prompt at each turn of the loop when all you have to do is update the coords.

Put the prompt creation out of the loop then define the coords in the loop with:
```lua
myPrompt:SetCoords(
    coords --[[ table | vec3 ]
)
```

**Comment by Sam8500** [comment]
I get an error now, I'm sorry if I'm misundestanding something simple but english isn't my first language haha 
![image](https://user-images.githubusercontent.com/99142544/167263754-4ebffdb0-64f2-4f72-aab5-984cf58980ec.png)

**Comment by TrAsKiN** [comment]
I am French too, let's continue this discussion on Discord, here is my ID: TrAsKiN#5255
